{
 "title": "Elder Scrolls Online - Account View",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "account", "label": "Account", "query": { "query": "label_values(account)" } },
   { "name": "interval", "label": "Interval", "query": "1d,7d,14d,30d" },
   {
    "name": "character",
    "query": {
     "query": "label_values({account=\"$account\",server=\"$server\"},character)"
    }
   },
   { "name": "server", "label": "Server", "query": { "query": "label_values(server)" } },
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Gold Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gold total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(eso_bank{account=\"$account\",server=\"$server\"})+sum(eso_character{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Gold Average"
      },
      {
       "expr": "min(eso_bank{account=\"$account\",server=\"$server\"})+sum(eso_character{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Gold Minimum"
      },
      {
       "expr": "max(eso_bank{account=\"$account\",server=\"$server\"})+sum(eso_character{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Gold Maximum"
      }
     ]
    },
    {
     "title": "Gold total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(eso_character{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Character"
      },
      {
       "expr": "avg(eso_bank{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Bank"
      },
      {
       "expr": "avg(eso_bank{account=\"$account\",server=\"$server\"})+sum(eso_character{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Gold earned vs spent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(eso_total_spent{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Spent"
      },
      {
       "expr": "sum(eso_total_earned{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Earned"
      }
     ]
    },
    {
     "title": "Gold earned total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(eso_guild_store_sales{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Guild store"
      },
      {
       "expr": "sum(eso_merchant_sales{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Merchant"
      },
      {
       "expr": "sum(eso_loot{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Loot"
      },
      {
       "expr": "sum(eso_quests_gold{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Quest"
      },
      {
       "expr": "sum(eso_gold_stolen{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Stolen"
      },
      {
       "expr": "sum(eso_fence_sales{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Fence"
      }
     ]
    },
    {
     "title": "Gold earned total %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(eso_guild_store_sales{account=\"$account\",server=\"$server\"}) / sum(eso_total_earned{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Guild store"
      },
      {
       "expr": "sum(eso_merchant_sales{account=\"$account\",server=\"$server\"}) / sum(eso_total_earned{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Merchant"
      },
      {
       "expr": "sum(eso_loot{account=\"$account\",server=\"$server\"}) / sum(eso_total_earned{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Loot"
      },
      {
       "expr": "sum(eso_quests_gold{account=\"$account\",server=\"$server\"}) / sum(eso_total_earned{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Quest"
      },
      {
       "expr": "sum(eso_gold_stolen{account=\"$account\",server=\"$server\"}) / sum(eso_total_earned{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Stolen"
      },
      {
       "expr": "sum(eso_fence_sales{account=\"$account\",server=\"$server\"}) / sum(eso_total_earned{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Fence"
      }
     ]
    },
    {
     "title": "Gold spent total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(eso_merchant_purchases{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Merchant"
      },
      {
       "expr": "sum(eso_riding_skills{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Riding Skills"
      },
      {
       "expr": "sum(eso_guild_store_purchases{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Guild Store"
      },
      {
       "expr": "sum(eso_bag_space_upgrades{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Bag Space"
      },
      {
       "expr": "sum(eso_wayshrine_travels{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Wayshrine Travel"
      },
      {
       "expr": "sum(eso_npc_dialogs{account=\"$account\",server=\"$server\"})",
       "legendFormat": "NPC Dialogs"
      },
      {
       "expr": "sum(eso_bounty_paid{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Bounty"
      },
      {
       "expr": "sum(eso_guild_store_fees{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Guild Store Fees"
      },
      {
       "expr": "sum(eso_resetting_attribute_points{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Resetting Attributes"
      },
      {
       "expr": "sum(eso_resetting_morphs{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Resetting Morphs"
      },
      {
       "expr": "sum(eso_resetting_skills{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Resetting Skills"
      },
      {
       "expr": "sum(eso_laundering_fees{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Laundering Fees"
      },
      {
       "expr": "sum(eso_buyback{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Buyback"
      }
     ]
    }
   ]
  },
  {
   "title": "Gold over time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Earned / Spent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(eso_total_earned{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Gold earned"
      },
      {
       "expr": "sum(increase(eso_total_spent{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Gold spent"
      }
     ]
    },
    {
     "title": "Gold earned by type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(eso_quests_gold{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Quests"
      },
      {
       "expr": "sum(increase(eso_guild_store_sales{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Guild Store"
      },
      {
       "expr": "sum(increase(eso_merchant_sales{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Merchant"
      },
      {
       "expr": "sum(increase(eso_loot{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Loot"
      },
      {
       "expr": "sum(increase(eso_gold_stolen{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Stolen"
      },
      {
       "expr": "sum(increase(eso_fence_sales{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Fence"
      }
     ]
    },
    {
     "title": "Gold earned %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(increase(eso_quests_gold{account=\"$account\",server=\"$server\"}[$interval])) / sum(increase(eso_total_earned{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Quests"
      },
      {
       "expr": "sum(increase(eso_guild_store_sales{account=\"$account\",server=\"$server\"}[$interval])) / sum(increase(eso_total_earned{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Guild Store"
      },
      {
       "expr": "sum(increase(eso_merchant_sales{account=\"$account\",server=\"$server\"}[$interval])) / sum(increase(eso_total_earned{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Merchant"
      },
      {
       "expr": "sum(increase(eso_loot{account=\"$account\",server=\"$server\"}[$interval])) / sum(increase(eso_total_earned{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Loot"
      },
      {
       "expr": "sum(increase(eso_gold_stolen{account=\"$account\",server=\"$server\"}[$interval])) / sum(increase(eso_total_earned{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Stolen"
      },
      {
       "expr": "sum(increase(eso_fence_sales{account=\"$account\",server=\"$server\"}[$interval])) / sum(increase(eso_total_earned{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Fence"
      }
     ]
    },
    {
     "title": "Gold spent by type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(eso_merchant_purchases{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Merchant"
      },
      {
       "expr": "sum(increase(eso_riding_skills{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Riding Skills"
      },
      {
       "expr": "sum(increase(eso_guild_store_purchases{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Guild Store"
      },
      {
       "expr": "sum(increase(eso_bag_space_upgrades{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Bag Space"
      },
      {
       "expr": "sum(increase(eso_wayshrine_travels{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Wayshrine Travels"
      },
      {
       "expr": "sum(increase(eso_npc_dialogs{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "NPC"
      },
      {
       "expr": "sum(increase(eso_bounty_paid{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Bounty"
      },
      {
       "expr": "sum(increase(eso_guild_store_fees{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Guild Store Fees"
      },
      {
       "expr": "sum(increase(eso_resetting_attribute_points{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Reset Attributes"
      },
      {
       "expr": "sum(increase(eso_resetting_morphs{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Reset Morphs"
      },
      {
       "expr": "sum(increase(eso_resetting_skills{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Reset Skills"
      },
      {
       "expr": "sum(increase(eso_laundering_fees{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Laundering Fees"
      },
      {
       "expr": "sum(increase(eso_buyback{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Buyback"
      }
     ]
    },
    {
     "title": "Gold spent %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(increase(eso_merchant_purchases{account=\"$account\",server=\"$server\"}[$interval])) / sum(increase(eso_total_spent{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Merchant"
      },
      {
       "expr": "sum(increase(eso_riding_skills{account=\"$account\",server=\"$server\"}[$interval])) / sum(increase(eso_total_spent{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Riding Skills"
      },
      {
       "expr": "sum(increase(eso_guild_store_purchases{account=\"$account\",server=\"$server\"}[$interval])) / sum(increase(eso_total_spent{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Guild Store"
      },
      {
       "expr": "sum(increase(eso_bag_space_upgrades{account=\"$account\",server=\"$server\"}[$interval])) / sum(increase(eso_total_spent{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Bag Space"
      },
      {
       "expr": "sum(increase(eso_wayshrine_travels{account=\"$account\",server=\"$server\"}[$interval])) / sum(increase(eso_total_spent{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Wayshrine Travels"
      },
      {
       "expr": "sum(increase(eso_npc_dialogs{account=\"$account\",server=\"$server\"}[$interval])) / sum(increase(eso_total_spent{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "NPC"
      },
      {
       "expr": "sum(increase(eso_bounty_paid{account=\"$account\",server=\"$server\"}[$interval])) / sum(increase(eso_total_spent{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Bounty"
      },
      {
       "expr": "sum(increase(eso_guild_store_fees{account=\"$account\",server=\"$server\"}[$interval])) / sum(increase(eso_total_spent{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Guild Store Fees"
      },
      {
       "expr": "sum(increase(eso_resetting_attribute_points{account=\"$account\",server=\"$server\"}[$interval])) / sum(increase(eso_total_spent{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Reset Attributes"
      },
      {
       "expr": "sum(increase(eso_resetting_morphs{account=\"$account\",server=\"$server\"}[$interval])) / sum(increase(eso_total_spent{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Reset Morphs"
      },
      {
       "expr": "sum(increase(eso_resetting_skills{account=\"$account\",server=\"$server\"}[$interval])) / sum(increase(eso_total_spent{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Reset Skills"
      },
      {
       "expr": "sum(increase(eso_laundering_fees{account=\"$account\",server=\"$server\"}[$interval])) / sum(increase(eso_total_spent{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Laundering Fees"
      },
      {
       "expr": "sum(increase(eso_buyback{account=\"$account\",server=\"$server\"}[$interval])) / sum(increase(eso_total_spent{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Buyback"
      }
     ]
    },
    {
     "title": "Profit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(eso_total_earned{account=\"$account\",server=\"$server\"}[$interval]))-sum(increase(eso_total_spent{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Profit"
      },
      { "expr": "0", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  { "title": "Endeavors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Endeavors Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(eso_completed_daily{account=\"$account\",server=\"$server\"})",
     "legendFormat": "Daily"
    },
    {
     "expr": "sum(eso_completed_weekly{account=\"$account\",server=\"$server\"})",
     "legendFormat": "Weekly"
    }
   ]
  },
  {
   "title": "Endeavors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum(increase(eso_completed_daily{account=\"$account\",server=\"$server\"} [$interval]))",
     "legendFormat": "Daily"
    },
    {
     "expr": "sum(increase(eso_completed_weekly{account=\"$account\",server=\"$server\"} [$interval]))",
     "legendFormat": "Weekly"
    }
   ]
  },
  {
   "title": "Quests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Repeatable quests total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "eso_repeatables_completed{account=\"$account\",server=\"$server\"}",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Repeatable quests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "increase(eso_repeatables_completed{account=\"$account\",server=\"$server\"}[$interval])",
       "legendFormat": "{{character}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tales of Tribute",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Play Time total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "eso_total_play_time{account=\"$account\",server=\"$server\"}",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Play Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(eso_total_play_time{account=\"$account\",server=\"$server\"}[$interval])",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Prestige obtained total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(eso_prestige_obtained{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Prestige obtained"
      }
     ]
    },
    {
     "title": "Turns Played total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(eso_turns_played{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Turns played"
      }
     ]
    },
    {
     "title": "Coins obtained total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(eso_obtained_coins{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Coins obtained"
      }
     ]
    },
    {
     "title": "Victories / Defeats total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(eso_victories{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Victories"
      },
      {
       "expr": "sum(eso_defeats{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Defeats"
      },
      {
       "expr": "sum(eso_victories_against_players_private_duel{account=\"$account\",server=\"$server\"}) +\r\nsum(eso_victories_against_players_ranked_competitive{account=\"$account\",server=\"$server\"}) +\r\nsum(eso_victories_against_players_unranked_causual{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Victories against players"
      },
      {
       "expr": "sum(eso_defeats_against_players_private_duel{account=\"$account\",server=\"$server\"}) +\r\nsum(eso_defeats_against_players_ranked_competitive{account=\"$account\",server=\"$server\"}) +\r\nsum(eso_defeats_against_players_unranked_causual{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Defeats against players"
      },
      {
       "expr": "sum(eso_victories_against_npcs{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Victories against NPCs"
      },
      {
       "expr": "sum(eso_defeats_against_npcs{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Defeats against NPCs"
      }
     ]
    }
   ]
  },
  {
   "title": "Experience",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Experience gained by source total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(eso_kills{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Kills"
      },
      {
       "expr": "sum(eso_quests{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Quests"
      },
      {
       "expr": "sum(eso_scripted_events{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Scripted Events"
      },
      {
       "expr": "sum(eso_world_boss_kills{account=\"$account\",server=\"$server\"})",
       "legendFormat": "World Boss"
      },
      {
       "expr": "sum(eso_keep_conquered_defeated{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Keep conquered"
      },
      {
       "expr": "sum(eso_lock_picking{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Lock picking"
      },
      {
       "expr": "sum(eso_misc{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Misc"
      },
      {
       "expr": "sum(eso_experience_points_gained{account=\"$account\",server=\"$server\"})-sum(eso_misc{account=\"$account\",server=\"$server\"})-sum(eso_lock_picking{account=\"$account\",server=\"$server\"})-sum(eso_keep_conquered_defeated{account=\"$account\",server=\"$server\"})-sum(eso_world_boss_kills{account=\"$account\",server=\"$server\"})-sum(eso_scripted_events{account=\"$account\",server=\"$server\"})-sum(eso_quests{account=\"$account\",server=\"$server\"})-sum(eso_kills{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "Experience gained per Character total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "eso_experience_points_gained{account=\"$account\",server=\"$server\"}",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Experience by character",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(eso_experience_points_gained{account=\"$account\",server=\"$server\"}[$interval])",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Experience by source ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(eso_kills{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Kills"
      },
      {
       "expr": "sum(increase(eso_quests{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Quests"
      },
      {
       "expr": "sum(increase(eso_scripted_events{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Scripted Events"
      },
      {
       "expr": "sum(increase(eso_world_boss_kills{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "World Boss"
      },
      {
       "expr": "sum(increase(eso_keep_conquered_defeated{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Keep conquered"
      },
      {
       "expr": "sum(increase(eso_lock_picking{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Lock picking"
      },
      {
       "expr": "sum(increase(eso_misc{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Misc"
      },
      {
       "expr": "sum(increase(eso_experience_points_gained{account=\"$account\",server=\"$server\"}[$interval]))-sum(increase(eso_misc{account=\"$account\",server=\"$server\"}[$interval]))-sum(increase(eso_lock_picking{account=\"$account\",server=\"$server\"}[$interval]))-sum(increase(eso_keep_conquered_defeated{account=\"$account\",server=\"$server\"}[$interval]))-sum(increase(eso_world_boss_kills{account=\"$account\",server=\"$server\"}[$interval]))-sum(increase(eso_scripted_events{account=\"$account\",server=\"$server\"}[$interval]))-sum(increase(eso_quests{account=\"$account\",server=\"$server\"}[$interval]))-sum(increase(eso_kills{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "Experience by source (char break down)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 19, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(eso_kills{account=\"$account\", character=\"$character\"}[$interval])",
       "legendFormat": "Kills {{character}}"
      },
      {
       "expr": "increase(eso_quests{account=\"$account\",character=\"$character\"}[$interval])",
       "legendFormat": "Quests {{character}}"
      },
      {
       "expr": "increase(eso_scripted_events{account=\"$account\",character=\"$character\"}[$interval])",
       "legendFormat": "Scripted Events {{character}}"
      },
      {
       "expr": "increase(eso_world_boss_kills{account=\"$account\",character=\"$character\"}[$interval])",
       "legendFormat": "World Boss {{character}}"
      },
      {
       "expr": "increase(eso_keep_conquered_defeated{account=\"$account\",character=\"$character\"}[$interval])",
       "legendFormat": "Keep conquered {{character}}"
      },
      {
       "expr": "increase(eso_lock_picking{account=\"$account\",character=\"$character\"}[$interval])",
       "legendFormat": "Lock Picking {{character}}"
      },
      {
       "expr": "increase(eso_misc{account=\"$account\",character=\"$character\"}[$interval])",
       "legendFormat": "Misc {{character}}"
      },
      {
       "expr": "increase(eso_experience_points_gained{account=\"$account\",character=\"$character\"}[$interval])-increase(eso_misc{account=\"$account\",character=\"$character\"}[$interval])-increase(eso_lock_picking{account=\"$account\",character=\"$character\"}[$interval])-increase(eso_keep_conquered_defeated{account=\"$account\",character=\"$character\"}[$interval])-increase(eso_world_boss_kills{account=\"$account\",character=\"$character\"}[$interval])-increase(eso_scripted_events{account=\"$account\",character=\"$character\"}[$interval])-increase(eso_quests{account=\"$account\",character=\"$character\"}[$interval])-increase(eso_kills{account=\"$account\",character=\"$character\"}[$interval])",
       "legendFormat": "Other {{character}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Combat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "NPCs killed total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort_desc(eso_npcs_killed{account=\"$account\",server=\"$server\"})",
       "legendFormat": "{{character}} "
      }
     ]
    },
    {
     "title": "NPCs killed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(eso_npcs_killed{account=\"$account\",server=\"$server\"}[$interval])",
       "legendFormat": "{{character}} "
      }
     ]
    },
    {
     "title": "Damage done total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort_desc(eso_damage_done{account=\"$account\",server=\"$server\"})",
       "legendFormat": "{{character}} "
      }
     ]
    },
    {
     "title": "Damage done",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(eso_damage_done{account=\"$account\",server=\"$server\"}[$interval])",
       "legendFormat": "{{character}} "
      }
     ]
    },
    {
     "title": "Damage taken total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "eso_damage_taken{account=\"$account\",server=\"$server\"}",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Damage taken",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(eso_damage_taken{account=\"$account\",server=\"$server\"}[$interval])",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Resurrections total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "eso_resurrections{account=\"$account\",server=\"$server\"}",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Resurrections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(eso_resurrections{account=\"$account\",server=\"$server\"}[$interval])",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Deaths total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "eso_deaths{account=\"$account\",server=\"$server\"}",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Deaths",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(eso_deaths{account=\"$account\",server=\"$server\"}[$interval])",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Target Dummy Damge total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "eso_damage_done_target_dummy{account=\"$account\",server=\"$server\"}",
       "legendFormat": "{{character}} "
      }
     ]
    },
    {
     "title": "Target Dummy Damage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(eso_damage_done_target_dummy{account=\"$account\",server=\"$server\"}[$interval])",
       "legendFormat": "{{character}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Healing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Healing done total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "eso_healing_done{account=\"$account\",server=\"$server\"}",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Healing done per interval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(eso_healing_done{account=\"$account\",server=\"$server\"}[$interval])",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Over Healing done total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "eso_overheal_done{account=\"$account\",server=\"$server\"}",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Over Healing done per interval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(eso_overheal_done{account=\"$account\",server=\"$server\"}[$interval])",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Heal taken total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "eso_healing_taken{account=\"$account\",server=\"$server\"}",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Heal taken per interval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(eso_healing_taken{account=\"$account\",server=\"$server\"}[$interval])",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Overhealing taken",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "eso_overheal_taken{account=\"$account\",server=\"$server\"}",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Overhealing taken per interval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(eso_overheal_taken{account=\"$account\",server=\"$server\"}[$interval])",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Heal vs Overheal done",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(eso_overheal_done{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Overheal"
      },
      {
       "expr": "sum(eso_healing_done{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Heal"
      }
     ]
    }
   ]
  },
  {
   "title": "Justice",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bounty total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(eso_total_bounty{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Total Bounty"
      },
      {
       "expr": "sum(eso_bounty_paid{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Bounty paid"
      }
     ]
    },
    {
     "title": "Bounty",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(eso_total_bounty{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Total Bounty"
      },
      {
       "expr": "sum(increase(eso_bounty_paid{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Bounty paid"
      }
     ]
    },
    {
     "title": "Bounty per Character total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "eso_total_bounty{account=\"$account\",server=\"$server\"}",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Stolen Items",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(eso_stolen_junk{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Junk"
      },
      {
       "expr": "sum(increase(eso_stolen_normal{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Normal"
      },
      {
       "expr": "sum(increase(eso_stolen_fine{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Fine"
      },
      {
       "expr": "sum(increase(eso_stolen_superior{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Superior"
      },
      {
       "expr": "sum(increase(eso_stolen_epic{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Epic"
      },
      {
       "expr": "sum(increase(eso_stolen_legendary{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Legendary"
      }
     ]
    },
    {
     "title": "Stolen Items total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(eso_stolen_epic{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Epic"
      },
      {
       "expr": "sum(eso_stolen_fine{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Fine"
      },
      {
       "expr": "sum(eso_stolen_junk{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Junk"
      },
      {
       "expr": "sum(eso_stolen_normal{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Normal"
      },
      {
       "expr": "sum(eso_stolen_legendary{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Legendary"
      },
      {
       "expr": "sum(eso_stolen_superior{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Superior"
      }
     ]
    }
   ]
  },
  {
   "title": "PvP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alliance Points gained total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "eso_alliance_points_gained{account=\"$account\",server=\"$server\"}",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Alliance points",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(eso_alliance_points_gained{account=\"$account\",server=\"$server\"}[$interval])",
       "legendFormat": "{{character}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Loot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loot total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(eso_armors{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Armors"
      },
      {
       "expr": "sum(eso_weapons{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Weapons"
      },
      {
       "expr": "sum(eso_enchanting_runes{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Enchanting Runes"
      },
      {
       "expr": "sum(eso_jewelry_crafting_materials{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Jewelry Crafting Material"
      },
      {
       "expr": "sum(eso_ingredients{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Ingredients"
      },
      {
       "expr": "sum(eso_soul_gems{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Soul Gems"
      },
      {
       "expr": "sum(eso_trophies{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Trophies"
      },
      {
       "expr": "sum(eso_foods{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Foods"
      },
      {
       "expr": "sum(eso_lock_picks{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Lock Picks"
      },
      {
       "expr": "sum(eso_lure{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Lure"
      },
      {
       "expr": "sum(eso_blacksmithing_materials{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Blacksmithing Materials"
      },
      {
       "expr": "sum(eso_woodworking_materials{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Woodworking Materials"
      },
      {
       "expr": "sum(eso_reagents{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Reagents"
      },
      {
       "expr": "sum(eso_style_material{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Style Material"
      },
      {
       "expr": "sum(eso_glyphs{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Glyphs"
      },
      {
       "expr": "sum(eso_drinks{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Drinks"
      },
      {
       "expr": "sum(eso_potions{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Potions"
      },
      {
       "expr": "sum(eso_trash{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Trash"
      },
      {
       "expr": "sum(eso_collectibles{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Collectibles"
      },
      {
       "expr": "sum(eso_recipes{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Recipes"
      }
     ]
    },
    {
     "title": "Loot",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(eso_armors{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Armors"
      },
      {
       "expr": "sum(increase(eso_weapons{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Weapons"
      },
      {
       "expr": "sum(increase(eso_enchanting_runes{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Enchanting Runes"
      },
      {
       "expr": "sum(increase(eso_jewelry_crafting_materials{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Jewelry Crafting Material"
      },
      {
       "expr": "sum(increase(eso_ingredients{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Ingredients"
      },
      {
       "expr": "sum(increase(eso_soul_gems{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Soul Gems"
      },
      {
       "expr": "sum(increase(eso_trophies{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Trophies"
      },
      {
       "expr": "sum(increase(eso_foods{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Foods"
      },
      {
       "expr": "sum(increase(eso_lock_picks{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Lock Picks"
      },
      {
       "expr": "sum(increase(eso_lure{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Lure"
      },
      {
       "expr": "sum(increase(eso_blacksmithing_materials{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Blacksmithing Materials"
      },
      {
       "expr": "sum(increase(eso_woodworking_materials{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Woodworking Materials"
      },
      {
       "expr": "sum(increase(eso_reagents{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Reagents"
      },
      {
       "expr": "sum(increase(eso_style_material{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Style Material"
      },
      {
       "expr": "sum(increase(eso_glyphs{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Glyphs"
      },
      {
       "expr": "sum(increase(eso_drinks{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Drinks"
      },
      {
       "expr": "sum(increase(eso_potions{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Potions"
      },
      {
       "expr": "sum(increase(eso_trash{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Trash"
      },
      {
       "expr": "sum(increase(eso_collectibles{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Collectibles"
      },
      {
       "expr": "sum(increase(eso_recipes{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Recipes"
      }
     ]
    }
   ]
  },
  { "title": "World Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "World Events Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(eso_dark_anchors_completed{account=\"$account\",server=\"$server\"})",
     "legendFormat": "Dark Anchors"
    },
    {
     "expr": "sum(eso_abyssal_geysers_completed{account=\"$account\",server=\"$server\"})",
     "legendFormat": "Abyssal Geysers"
    },
    {
     "expr": "sum(eso_harrowstorms_completed{account=\"$account\",server=\"$server\"})",
     "legendFormat": "Harrowstorms"
    },
    {
     "expr": "sum(eso_volcano_vents_completed{account=\"$account\",server=\"$server\"})",
     "legendFormat": "Volcano Vents"
    }
   ]
  },
  {
   "title": "World Events Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(eso_dark_anchors_completed{account=\"$account\",server=\"$server\"} [$interval]))",
     "legendFormat": "Dark Anchors"
    },
    {
     "expr": "sum(increase(eso_abyssal_geysers_completed{account=\"$account\",server=\"$server\"} [$interval]))",
     "legendFormat": "Abyssal Geysers"
    },
    {
     "expr": "sum(increase(eso_harrowstorms_completed{account=\"$account\",server=\"$server\"} [$interval]))",
     "legendFormat": "Harrowstorms"
    },
    {
     "expr": "sum(increase(eso_volcano_vents_completed{account=\"$account\",server=\"$server\"} [$interval]))",
     "legendFormat": "Volcano Vents"
    }
   ]
  },
  {
   "title": "Globetrotter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fast Travels total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "eso_fast_travels{account=\"$account\",server=\"$server\"}",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Fast Travels",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(eso_fast_travels{account=\"$account\",server=\"$server\"}[$interval])",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Books read total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "eso_books_letters_read{account=\"$account\",server=\"$server\"}",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Books read",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(eso_books_letters_read{account=\"$account\",server=\"$server\"}[$interval])",
       "legendFormat": "{{character}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Test",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bank Gold per Character",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "eso_bank{account=\"$account\",server=\"$server\"}",
       "legendFormat": "{{character}}"
      },
      {
       "expr": "avg(eso_bank{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "Bank Gold per Character",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "eso_bank{account=\"$account\",server=\"$server\"}",
       "legendFormat": "{{character}}"
      },
      {
       "expr": "avg(eso_bank{account=\"$account\",server=\"$server\"})",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "Guild store purchases per interval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(eso_guild_store_purchases{account=\"$account\",server=\"$server\"}[$interval])",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Character Gold",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "eso_character{account=\"$account\",server=\"$server\"}",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "Gold earned per Interval (new time series panel)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(eso_quests_gold{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Quests"
      },
      {
       "expr": "sum(increase(eso_guild_store_sales{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Guild Store"
      },
      {
       "expr": "sum(increase(eso_merchant_sales{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Merchant"
      },
      {
       "expr": "sum(increase(eso_loot{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Loot"
      },
      {
       "expr": "sum(increase(eso_gold_stolen{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Stolen"
      },
      {
       "expr": "sum(increase(eso_fence_sales{account=\"$account\",server=\"$server\"}[$interval]))",
       "legendFormat": "Fence"
      }
     ]
    },
    {
     "title": "Guild store sales per interval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(eso_guild_store_sales{account=\"$account\",server=\"$server\"}[$interval])",
       "legendFormat": "{{character}}"
      }
     ]
    },
    {
     "title": "new time series panel with sort",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (account)(increase(eso_total_earned[7d]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true
  }
 ]
}